/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-104375-g77970abb71-20211017"
#endif /* AVUTIL_FFVERSION_H */
