package st

/*
#cgo CFLAGS: -I./../sdl/include
#cgo LDFLAGS: -L./../sdl/lib -lSDL2 -lSDL2main -lSDL2_image -lSDL2_ttf -lSDL2_mixer

#include <SDL.h>
#include <SDL_image.h>
#include <SDL_ttf.h>
#include <SDL_mixer.h>
*/
import "C"

type SDL_Window C.SDL_Window
type SDL_Renderer C.SDL_Renderer
type SDL_Event C.SDL_Event

const (
	SDL_INIT_EVERYTHING = C.SDL_INIT_EVERYTHING
)

const (
	SDL_WINDOWPOS_CENTERED = C.SDL_WINDOWPOS_CENTERED
)

const (
	SDL_WINDOW_SHOWN       = C.SDL_WINDOW_SHOWN
	SDL_WINDOW_RESIZABLE   = C.SDL_WINDOW_RESIZABLE
	SDL_WINDOW_INPUT_FOCUS = C.SDL_WINDOW_INPUT_FOCUS
	SDL_WINDOW_MOUSE_FOCUS = C.SDL_WINDOW_MOUSE_FOCUS
)

const (
	SDL_RENDERER_ACCELERATED   = C.SDL_RENDERER_ACCELERATED
	SDL_RENDERER_PRESENTVSYNC  = C.SDL_RENDERER_PRESENTVSYNC
	SDL_RENDERER_TARGETTEXTURE = C.SDL_RENDERER_TARGETTEXTURE
)
